name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  run-hello-world-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello-world.sh script
        run: ./.github/scripts/hello-world.sh
        shell: bash
