name: Log secrets
on: [workflow_dispatch]

jobs:

  log-api-key:
    runs-on: ubuntu-latest
    steps:
      - name: Try logging API key
        run: echo ${{ secrets.API_KEY }}

  log-password:
    runs-on: ubuntu-latest
    steps:
      - name: Try logging passwords
        run: echo ${{ secrets.PASSWORD }}

  log-non-existing-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Try logging non-existing secret
        run: echo ${{ secrets.NON_EXISTING }}
