name: Reusable (called) Workflow 0

on: 
  workflow_call:
    inputs:
      parameter-0:
        required: false
        type: number
    secrets:
      password:
        required: true

jobs:

  reusable-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Echo input parameter-0
        run: echo ${{ inputs.parameter-0 }}
      - name: Echo secret password
        run: echo ${{ secrets.password }}
