# .github/workflows/stale.yml
name: Detect stales

on:
  schedule:
  - cron: '0 8 * * *'

jobs:
  detect-stales:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue was detected.'
        stale-pr-message: 'Stale pull request was detected.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
